/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gtelefoniastocktaking;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import static gtelefoniastocktaking.hacer_ventas.count;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
/**
 *
 * @author Vinicio
 */
public class ConfirmarVenta extends javax.swing.JFrame {
public static Double sumaT;
Connection cnx = null;
String url = "jdbc:mysql://localhost:3306/bd_farm";
String user = "root";
String pass = "";
int cant, lastID;
private int x;
private int y;
FileOutputStream ficheroPdf;
String destPDf;
Double Prec, totalVenta ;
int cantidad, unidadesDeseadas = 0;
String Mark, ModelS, PriceSale, totalV, unit;
Color CBTNmenu =new Color(241,118,36);
Color CBTNFocus =new Color(238,98,5);
Border focus = new LineBorder(CBTNFocus, 86);
Color grisMoved =new Color(180,180,180);
Color grisborde =new Color(224,224,224);
Color grisPress =new Color(179,179,179);
Color ColorFont =new Color(123,123,123);
Color ColorSalida =new Color(255,102,04);
Color ColorSalida2 =new Color(2,72,142);
BaseColor NameC = new BaseColor(126,126,126);
BaseColor TipoC = new BaseColor(134,134,134);
Border thickBorde = new LineBorder(Color.WHITE, 4);
public static String TTV, usrs;      
public static String[][] array_String;
public static String[][] array_tipo;
public static Double[][] array_Double; 
public static int count, oFF;
public static ArrayList<Integer> reducU = new ArrayList<>();
public static String clin;

    public ConfirmarVenta(String TT, String[][] Array_String,String[][] Array_tip, Double[][] Array_Double, String user, ArrayList<Integer> cantidadD, int off, String cli) {
        initComponents();
         setLocationRelativeTo(null);
          JTableHeader th; 
          jLabel3.setToolTipText(null);
          jLabel2.setToolTipText(null);
        th = destino.getTableHeader(); 
        Font fuente = new Font("Microsoft Yi Baiti", Font.PLAIN, 21); 
        destino.setRowHeight(25);
        th.setFont(fuente); 
        jButton1.setBorder(thickBorde);
        jButton3.setBorder(thickBorde);
        usrs=user;
        TTV=TT;
        oFF=off;
        reducU = cantidadD;
array_String = Array_String;
array_tipo = Array_tip;
array_Double = Array_Double;
clin=cli;
jLabel22.setText(TTV);
 DefaultTableModel modelo = (DefaultTableModel) destino.getModel();
 Object [] fila=new Object[8]; 
    int i = 0;
    int j = 0;
        for (i = 0; i <array_String.length; i++) {
        for (j = 0; j < 3; j++) {
        fila[j]=array_String[i][j]; 
        }
        for (j = 0; j < 4; j++) {
        fila[j+3]=array_Double[i][j]; 
        
        }
         for (j = 0; j < 1; j++) {
        fila[j+7]=array_tipo[i][j]; 
        
        }
        modelo.addRow(fila); 
        }   
         
         destino.setModel(modelo);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        destino = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirmar Venta");
        setMinimumSize(new java.awt.Dimension(983, 610));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 728));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(23, 23, 23));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Regresar");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 150, 60));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(123, 123, 123));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 0, 40, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setFocusPainted(false);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 0, 40, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 123, 123));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setToolTipText(""); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1325, 0, 43, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setFocusPainted(false);
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1325, 0, 43, 40));

        jLabel1.setText(".");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 10, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 231, 231));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONFIRMAR VENTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/grisFondo.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(18, 18, 18));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("¿Esta seguro de realizar esta venta?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 580, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/blanco.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 370, 40));

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Q");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 30, 60));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Confirmar");
        jLabel38.setToolTipText("");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel38.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel38MouseMoved(evt);
            }
        });
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel38MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel38MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 160, 60));

        jButton9.setBackground(new java.awt.Color(241, 118, 36));
        jButton9.setForeground(new java.awt.Color(3, 64, 124));
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setFocusPainted(false);
        jButton9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton9MouseMoved(evt);
            }
        });
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 160, 60));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/blancoE2.jpg"))); // NOI18N
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel35MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 150, 60));

        jLabel18.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(23, 23, 23));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Datos de pago");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 180, 40));

        jLabel22.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 30)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 170, 60));

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 0, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Regresar para realizar cambios en la venta");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 30));

        jLabel23.setFont(new java.awt.Font("Microsoft Tai Le", 0, 10)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Si esta seguro de realizar la venta, presione ");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("INSTRUCCIONES");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft Tai Le", 0, 10)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Confirmar y este proceso terminará o presione");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 30));

        jLabel29.setFont(new java.awt.Font("Microsoft Tai Le", 0, 10)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Confirmar y este proceso terminará o presione");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 30));

        jLabel30.setFont(new java.awt.Font("Microsoft Tai Le", 0, 10)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Regresar para realizar cambios en la venta");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/solid-orange-background.jpg"))); // NOI18N
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 690));

        destino.setBackground(new java.awt.Color(153, 153, 153));
        destino.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 18)); // NOI18N
        destino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Producto", "Precio", "Descuento", "Unidades", "Total", "Tipo Cliente"
            }
        ));
        jScrollPane1.setViewportView(destino);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 1110, 220));

        jLabel32.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 30)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(23, 23, 23));
        jLabel32.setText("Total a pagar:");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 60));

        jLabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 64, 64), 1, true));
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 580, 80));

        jLabel33.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 28)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(32, 32, 32));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Artículos para vender");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 270, 50));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/blanco.jpg"))); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel34MousePressed(evt);
            }
        });
        jLabel34.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel34MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 700, 40));

        jLabel8.setForeground(new java.awt.Color(126, 126, 126));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/grisFondo.jpg"))); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel8MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 1150, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        Border thickBorder = new LineBorder(grisPress, 54);
        jButton1.setBorder(thickBorder);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        Border thickBorder = new LineBorder(grisborde, 54);
        jButton1.setBorder(thickBorder);
        jButton3.setBorder(thickBorde);
        jLabel3.setForeground(ColorFont);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        Border thickBorder = new LineBorder(grisPress, 54);
        jButton1.setBorder(thickBorder);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        Border thickBorder = new LineBorder(grisborde, 54);
        jButton1.setBorder(thickBorder);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        Border thickBorder = new LineBorder(grisborde, 54);
        jButton1.setBorder(thickBorder);
        jButton3.setBorder(thickBorde);
        jLabel2.setForeground(Color.BLACK);
        jLabel3.setForeground(ColorFont);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        Border thickBorder = new LineBorder(ColorSalida2, 54);
        jButton3.setBorder(thickBorder);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        Border thickBorder = new LineBorder(ColorSalida2, 54);
        jButton3.setBorder(thickBorder);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        Border thickBorder = new LineBorder(ColorSalida, 54);
        jButton3.setBorder(thickBorder);
        jButton1.setBorder(thickBorde);
        jLabel2.setForeground(ColorFont);
        jLabel3.setForeground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        Border thickBorder = new LineBorder(Color.BLUE, 54);
        jButton3.setBorder(thickBorder);
        jButton1.setBorder(thickBorde);
        jLabel3.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
     
                // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7KeyPressed

    private void jLabel35MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35MouseReleased

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
  Border thickBorder = new LineBorder(CBTNmenu, 60);
        jButton9.setBorder(thickBorder);

               // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jLabel38MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MousePressed

    private void jLabel38MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseReleased
insertProd();    
        
try {
            File path;
            path = new File(destPDf );
            Desktop.getDesktop().open(path);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseReleased

    private void jLabel38MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseMoved
jLabel38.setToolTipText(null);  
jButton9.setBorder(focus);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseMoved

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MousePressed

    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseReleased

    private void jButton9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseMoved

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseMoved
 Border thickBorder = new LineBorder(CBTNmenu, 60);
        jButton9.setBorder(thickBorder);
        
               // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseMoved

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseDragged

    private void jLabel34MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseDragged
this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseDragged

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
x = evt.getX();
                y = evt.getY();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MousePressed
   x = evt.getX();
                y = evt.getY();     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MousePressed

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
Border thickBorde = new LineBorder(Color.WHITE, 4);
jButton3.setBorder(thickBorde);  
jLabel3.setForeground(Color.gray);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
Border thickBorde = new LineBorder(Color.WHITE, 4);
jButton1.setBorder(thickBorde);  
jLabel2.setForeground(Color.gray);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarVenta(TTV,array_String,array_tipo,array_Double,usrs, reducU, oFF, clin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable destino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public void insertProd(){
       
            Calendar fecha = new GregorianCalendar();
            
            int año = fecha.get(Calendar.YEAR);
            int mes = fecha.get(Calendar.MONTH);
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
            //---------------------------------------------------------------------------------------------------
            //--------------inserto en factura ------------------------------------------------------------------
            try {
                Connection conn = DriverManager.getConnection(url, user, pass);
                String sql = "INSERT INTO factura (codigo_factura, usuario, total,fecha) values (NULL, ?, ?, ?)";
                PreparedStatement stmt = conn.prepareStatement(sql);
                
                stmt.setString(1,usrs);
                stmt.setString(2, TTV);
                stmt.setString(3,año+"-"+(mes+1)+"-"+dia);
                stmt.executeUpdate();
                stocktaking.test=1;       
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex);
            }
            //---------------------------------------------------------------------------------------------------
            //--------------select ultimo ID------------------------------------------------------------------
            try{
                 Connection con = DriverManager.getConnection(url, user, pass);
            String query = "SELECT *FROM factura";
            Statement sts = con.prepareStatement(query);
            ResultSet rest = sts.executeQuery(query);
            
           while (rest.next()){
            lastID = rest.getInt(1);
            
            }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
            
            //---------------------------------------------------------------------------------------------------
            //--------------inserto en Detallefactura ------------------------------------------------------------------
            try{
                for(int i=0; i<destino.getRowCount();i++){
             Connection conex = DriverManager.getConnection(url, user, pass);
               String sql = "INSERT INTO Detalle_factura (codigo_detalle_factura, codigo_factura,codigo_producto, producto,categoria, unidades,precio_venta,descuento,precio_total) values (null, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conex.prepareStatement(sql);
            
            stmt.setInt(1,lastID);          
            stmt.setString(2, (String) destino.getValueAt(i,0));
            stmt.setString(3,(String) destino.getValueAt(i,1));
            stmt.setString(4,(String) destino.getValueAt(i,2));
            stmt.setDouble(5,(Double) destino.getValueAt(i,3));
            stmt.setDouble(6,(Double) destino.getValueAt(i,4));
            stmt.setDouble(7,(Double) destino.getValueAt(i,5));
            
            stmt.executeUpdate();
            
           }
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
            //---------------------------------------------------------------------------------------------------
            //--------------Update producto ------------------------------------------------------------------
            
 Connection cnx = null;
       
 try {
      for(int i=0; i<destino.getRowCount();i++){
     Class.forName("com.mysql.jdbc.Driver");
     cnx = DriverManager.getConnection(url, user,pass);
     String query = "update producto set Unidades = ? where Modelo = ?";
      PreparedStatement preparedStmt = cnx.prepareStatement(query);
      preparedStmt.setInt   (1, reducU.get(i));
      preparedStmt.setString(2, (String) destino.getValueAt(i,1));

      // execute the java preparedstatement
      preparedStmt.executeUpdate();
      
      cnx.close();
      
      hacer_ventas.count=2;
      
            this.dispose();
          DefaultTableModel dm = (DefaultTableModel)hacer_ventas.jTable1.getModel();
     while(dm.getRowCount() > 0)
     {
        dm.removeRow(0);
        //ventas.llenarCtipo();
        count=1;
        hacer_ventas.jLabel5.setText("");
     }
     pdf();     
            }
          }
          catch (Exception e)
          {
              JOptionPane.showMessageDialog(this,e);
          }
       //---------------------------------------------------------------------------------------------------
            //-------------- Truncate tablaux ------------------------------------------------------------------
      try{
             Connection conex = DriverManager.getConnection(url, user, pass);
        String Qury = "TRUNCATE tabla_aux";
        Statement sts =  conex.createStatement();
        sts.executeUpdate(Qury);
           }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
            }
         


public void pdf(){
    PdfWriter writer = null;
    String NameUSer="Usuario";
    com.itextpdf.text.Font f=new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.TIMES_ROMAN,50.0f,com.itextpdf.text.Font.UNDERLINE,BaseColor.RED);
    Calendar fecha = new GregorianCalendar();
    String TIPc = String.valueOf(destino.getValueAt(0,6));        
            int año = fecha.get(Calendar.YEAR);
            int mes = fecha.get(Calendar.MONTH)+1;
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
    
        Document documento = new Document(PageSize.A4); 
        documento.setMargins(0, 0, 50, 100);
    
    try 
    {
    ficheroPdf = new FileOutputStream("C:\\Users\\"+NameUSer+"\\Documents\\PDFVentas\\Comprobante - "+lastID+".PDF");
   destPDf=("C:\\Users\\"+NameUSer+"\\Documents\\PDFVentas\\Comprobante - "+lastID+".PDF");
   writer = PdfWriter.getInstance(documento,ficheroPdf);
   
    }
    catch (Exception ex) 
    {
     JOptionPane.showMessageDialog(this,ex.toString());
    }
try{
    documento.open();
  
         Image imagen = Image.getInstance("C:\\Users\\"+NameUSer+"\\Pictures\\BarraGT.png");
         imagen.scaleAbsolute(600f, 85f);
         imagen.setAlignment(Element.ALIGN_TOP);
          imagen.setAlignment(Element.ALIGN_CENTER);
          Paragraph parrafo1 = new Paragraph("14 calle 9-11 zona 3, Quetzaltenango.");
          Paragraph parrafo2 = new Paragraph("41518382 - 59266021");
          Paragraph parrafo3 = new Paragraph("                                                 ");
          Paragraph totVT = new Paragraph("TOTAL VENTA: Q "+jLabel22.getText());//Paragraph parrafo4 = new Paragraph("Fecha de Emisión: "+ dia+"/"+(mes+1)+"/"+año);
          parrafo1.setAlignment(1);
          parrafo2.setAlignment(1);
          
            PdfPTable table = new PdfPTable(7);     
            PdfPTable table2 = new PdfPTable(7);
            PdfPTable table3 = new PdfPTable(4);
            PdfPTable tCliente = new PdfPTable(7); 
            
            table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell celdaX1 = new PdfPCell(new Paragraph(" NOMBRE CLIENTE"));
            PdfPCell celdaX2 = new PdfPCell(new Paragraph(" TIPO DE CLIENTE"));
            PdfPCell datoX1 = new PdfPCell(new Paragraph(clin));
            PdfPCell datoX2 = new PdfPCell(new Paragraph(TIPc));
            
            celdaX1.setBorder(0);
            celdaX1.setBackgroundColor(NameC);
            celdaX1.setColspan(2);
            celdaX1.setHorizontalAlignment(Element.ALIGN_LEFT);
            datoX1.setBorder(0);
            datoX1.setBackgroundColor(NameC);
            datoX1.setColspan(2);
            datoX1.setHorizontalAlignment(Element.ALIGN_CENTER);
            celdaX2.setBorder(0);
            celdaX2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            celdaX2.setColspan(2);
            celdaX2.setHorizontalAlignment(Element.ALIGN_LEFT);
            datoX2.setBorder(0);
            datoX2.setBackgroundColor(BaseColor.LIGHT_GRAY);
            datoX2.setColspan(1);
            datoX2.setHorizontalAlignment(Element.ALIGN_CENTER);
            tCliente.addCell(celdaX1);
            tCliente.addCell(datoX1);
            tCliente.addCell(celdaX2);
            tCliente.addCell(datoX2);
            
            
            tCliente.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell celda1 = new PdfPCell(new Paragraph("FECHA"));
            PdfPCell celda2 = new PdfPCell(new Paragraph("COMPROBANTE"));
            PdfPCell celda3 = new PdfPCell(new Paragraph("VENDEDOR"));
            PdfPCell celda4 = new PdfPCell(new Paragraph("000" + Integer.toString(lastID)));
            PdfPCell celda5 = new PdfPCell(new Paragraph(usrs));
           
            // cuantas columnas ocupa la celda
            celda1.setBorder(0);
            celda1.setBackgroundColor(BaseColor.GRAY);
            celda1.setColspan(3);
            celda1.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(celda1);
            
            celda2.setBorder(0);celda2.setBackgroundColor(BaseColor.GRAY);
            celda2.setColspan(2);
            celda2.setRowspan(2);
            celda2.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(celda2);
            
            celda3.setBorder(0);
            celda3.setBackgroundColor(BaseColor.GRAY);
            celda3.setColspan(3);
            celda3.setRowspan(2);
            celda3.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(celda3);
            
            celda4.setColspan(2);
            celda4.setRowspan(2);
            celda4.setHorizontalAlignment(Element.ALIGN_CENTER);
            
            celda5.setColspan(3);
            celda5.setRowspan(2);
            celda5.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_LEFT);
            table.addCell("DIA");
            table.addCell("MES");
            table.addCell("AÑO");
            table2.addCell(Integer.toString(dia));
            table2.addCell(Integer.toString(mes));
            table2.addCell(Integer.toString(año));
            table2.addCell(celda4);
            table2.addCell(celda5);

            //Agregamos la imagen al documento.
          Class.forName("com.mysql.jdbc.Driver");
          cnx = DriverManager.getConnection(url, user,pass);
          Statement stmt = cnx.createStatement(); 
          String sql = "Select Tipo,Marca,Modelo,Unidades,Precio,Precio_x_Unidades from detalle_factura where idFactura='"+lastID+"'";
          ResultSet query = stmt.executeQuery(sql);  
          PdfPTable LogTable = new PdfPTable(6);
          PdfPCell cab1 = new PdfPCell(new Paragraph("Tipo"));
            PdfPCell cab2 = new PdfPCell(new Paragraph("Marca"));
            PdfPCell cab3 = new PdfPCell(new Paragraph("Modelo"));
            PdfPCell cab4 = new PdfPCell(new Paragraph("Precio"));
            PdfPCell cab5 = new PdfPCell(new Paragraph("Unidades"));
            PdfPCell cab6 = new PdfPCell(new Paragraph("PrecXunids"));
          cab1.setBackgroundColor(BaseColor.GRAY); 
          cab2.setBackgroundColor(BaseColor.GRAY);
          cab3.setBackgroundColor(BaseColor.GRAY);
          cab4.setBackgroundColor(BaseColor.GRAY);
          cab5.setBackgroundColor(BaseColor.GRAY);
          cab6.setBackgroundColor(BaseColor.GRAY);
         LogTable.addCell(cab1);
          LogTable.addCell(cab2);
          LogTable.addCell(cab3);
          LogTable.addCell(cab4);
          LogTable.addCell(cab5);
          LogTable.addCell(cab6);
          Paragraph parraf1 = new Paragraph("DETALLE DE VENTA");
          parraf1.setAlignment(Element.ALIGN_CENTER);
         
          PdfPCell table_cell;  
         while (query.next()) {         
             String tip = query.getString("Tipo");  
                 table_cell=new PdfPCell(new Phrase(tip));  
                 LogTable.addCell(table_cell);
                   String vendr = query.getString("Marca");  
                 table_cell=new PdfPCell(new Phrase(vendr));  
                 LogTable.addCell(table_cell);
                 String Username = query.getString("Modelo");  
                 table_cell=new PdfPCell(new Phrase(Username));  
                 LogTable.addCell(table_cell);  
                 String ipaddress=query.getString("Unidades");  
                 table_cell=new PdfPCell(new Phrase(ipaddress));  
                 LogTable.addCell(table_cell);  
                String prec=query.getString("Precio");  
                 table_cell=new PdfPCell(new Phrase(prec));  
                 LogTable.addCell(table_cell); 
                  String precUnid=query.getString("Precio_x_Unidades");  
                 table_cell=new PdfPCell(new Phrase(precUnid));  
                 LogTable.addCell(table_cell); 
         }  
         /* Attach report table to PDF */  
           
         /* Close all DB related objects */  
         query.close();  
         stmt.close();   
         cnx.close(); 
            documento.add(imagen);
                  documento.add(parrafo1);
                  documento.add(parrafo2);
                  documento.add(parrafo3);
                  documento.add(table);
                  documento.add(table2);
                  documento.add(parrafo3);
                  documento.add(tCliente);
                  documento.add(parrafo3);
                  documento.add(parraf1);
                  documento.add(parrafo3);
                   documento.add(LogTable);
                    documento.add(parrafo3);
                   totVT.setAlignment(Element.ALIGN_CENTER);
                   documento.add(totVT);
writer.setPageEvent(new MyFooter());
    documento.close();
    
}catch(Exception ex){
    System.out.println(ex.toString());
}
 
}




  class MyFooter extends PdfPageEventHelper {
    public void onEndPage(PdfWriter writer, Document document) {
  float fntSize, f1;
    fntSize = 18.7f;
    f1=16f;
     ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_CENTER, new Phrase("Gracias por su Preferencia",FontFactory.getFont(FontFactory.COURIER, fntSize)), 290, 110, 0);
    ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_CENTER, new Phrase("Dirección: 14 calle 9-11 zona 3, Quetzaltenango.",FontFactory.getFont(FontFactory.COURIER, f1)), 290, 85, 0);
    ColumnText.showTextAligned(writer.getDirectContent(), Element.ALIGN_CENTER, new Phrase("Teléfonos:  41518382 - 59266021",FontFactory.getFont(FontFactory.COURIER, f1)), 290, 60, 0);
  
    }
}
  
}

