/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gtelefoniastocktaking;

import gtelefoniastocktaking.mensajesSYS.cantidadMAyor;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vinicio
 */
public class hacer_ventas extends javax.swing.JFrame {
 JTable tblOrigen;
 public static int test2=1;
public static Double sumaT;
Connection cnx,conI = null;
String url = "jdbc:mysql://localhost:3306/bd_farm";
String user = "root";
String pass = "";
int cant,operacion1, aux;
public static int count;
  String ID, MK, MD, PRD, search;
  int UD;
  Double PC, PV, PG;
String auxST ;
public String cdp, Cliente;
private int x;
private int y;
public static String cod_prod,categor,product, tipoVent;
Double PreV, PreMay, PreOro, descu,totalVenta ;
int cantidad, unidadesDeseadas = 0, auxBT=0,auxBTNar=0;
String totalV, unit;
Color CBTNFocus =new Color(243,98,1);
Color focusAdd =new Color(0,120,240);
Color focusDel =new Color(198,17,17);
Border focus = new LineBorder(CBTNFocus, 86);
Border focusA = new LineBorder(focusAdd, 86);
Border focusD = new LineBorder(focusDel, 86);
Color CBTNmenu =new Color(241,118,36);
Color add =new Color(0,102,204);
Color delete =new Color(172,26,26);
Color Nums =new Color(153,153,153);
Color grisMoved =new Color(180,180,180);
Color grisborde =new Color(224,224,224);
Color grisPress =new Color(179,179,179);
Color ColorPlanoBT =new Color(255,102,04);
Color ColorFont =new Color(123,123,123);
Color ColorSalida =new Color(0,102,204);
Color ColorSalida2 =new Color(2,72,142);
Border thickBorde = new LineBorder(Color.WHITE, 4);
Border bordePlano= new LineBorder(ColorPlanoBT, 4);
public static String[][] array_String;
public static String[][] array_Tipo;
public static String NN;
public static Double[][] array_Double; 
ArrayList<Integer> units = new ArrayList<>();
    public hacer_ventas(String N) {
        initComponents();
         setLocationRelativeTo(null);
        jButton1.setBorder(thickBorde);
        jButton3.setBorder(thickBorde);
        NN=cdp;
        JTableHeader th; 
        th = jTable1.getTableHeader(); 
        Font fuente = new Font("Microsoft Yi Baiti", Font.PLAIN, 22); 
        th.setFont(fuente); 
        jLabel14.setVisible(false);
        jLabel6.setVisible(false);
        jLabel5.setVisible(false);
        jLabel3.setToolTipText(null);
        jLabel40.setToolTipText(null);
        jLabel39.setToolTipText(null);
find.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lcd = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        find = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas");
        setMinimumSize(new java.awt.Dimension(891, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 728));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(123, 123, 123));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1284, 0, 40, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1284, 0, 40, 40));

        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Yi Baiti", 0, 22), new java.awt.Color(142, 142, 142))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 550, 70));

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox2.setText("Precio Mayoreo");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox3.setText("Precio Oro");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 145, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 123, 123));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<<");
        jLabel3.setToolTipText(""); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1324, 0, 40, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/shopping-cart.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 30, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1324, 0, 41, 40));

        jLabel1.setText(".");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 750, 10, -1));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 231, 231));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REALIZAR VENTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/blanco.jpg"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 510, 40));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Buscar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 140, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/azulBarra.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 140, 50));

        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/magnifier.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 30, 40));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("+");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel20MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 70, 70));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("-");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel21MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 70, 70));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 70, 70));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 70, 70));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("Descuento");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 145, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 38, 38));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Número de unidades");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 200, 30));

        jTable1.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Categoria", "Producto", "Precio", "Descuento", "Unidades", "Total", "Tipo Cliente"
            }
        ));
        jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTable1MouseMoved(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1340, 220));

        jLabel5.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 54)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 93, 14));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 210, 80));

        jLabel6.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(28, 28, 28));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Venta ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 270, 80));

        lcd.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 26)); // NOI18N
        lcd.setForeground(new java.awt.Color(102, 102, 102));
        lcd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lcd.setText("0");
        lcd.setBorder(null);
        lcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcdActionPerformed(evt);
            }
        });
        lcd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lcdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lcdKeyReleased(evt);
            }
        });
        getContentPane().add(lcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 60, 70));

        jLabel14.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 54)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(243, 93, 14));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Q");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 40, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/AZUL.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Realizar Venta");
        jLabel38.setToolTipText("");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel38MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel38MouseReleased(evt);
            }
        });
        jLabel38.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel38MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 640, 210, 70));

        find.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 26)); // NOI18N
        find.setForeground(new java.awt.Color(102, 102, 102));
        find.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        find.setBorder(null);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                findKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                findKeyReleased(evt);
            }
        });
        getContentPane().add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 280, 50));

        jButton9.setBackground(new java.awt.Color(241, 118, 36));
        jButton9.setForeground(new java.awt.Color(3, 64, 124));
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.setFocusPainted(false);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });
        jButton9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton9MouseMoved(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 640, 210, 70));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Eliminar Artículo");
        jLabel39.setToolTipText("");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel39MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel39MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel39MouseReleased(evt);
            }
        });
        jLabel39.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel39MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 210, 70));

        jButton10.setBackground(new java.awt.Color(172, 26, 26));
        jButton10.setForeground(new java.awt.Color(3, 64, 124));
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton10.setFocusPainted(false);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton10MouseReleased(evt);
            }
        });
        jButton10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton10MouseMoved(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 210, 70));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Agregar Artículo");
        jLabel40.setToolTipText("");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel40MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel40MouseReleased(evt);
            }
        });
        jLabel40.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel40MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 320, 210, 70));

        jButton11.setBackground(new java.awt.Color(0, 102, 204));
        jButton11.setForeground(new java.awt.Color(3, 64, 124));
        jButton11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton11.setFocusPainted(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton11MouseReleased(evt);
            }
        });
        jButton11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton11MouseMoved(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 320, 210, 70));

        jTable2.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Marca", "Modelo", "Precio", "Unidades", "Total", "Tipo Cliente"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jTable2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTable2MouseMoved(evt);
            }
        });
        jTable2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable2PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1340, 180));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/grisFondo.jpg"))); // NOI18N
        jLabel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel17MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, 690));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/blanco.jpg"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel10MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 560, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        Border thickBorder = new LineBorder(grisPress, 54);
        jButton1.setBorder(thickBorder);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        Border thickBorder = new LineBorder(grisborde, 54);
        jButton1.setBorder(thickBorder);
        jButton3.setBorder(thickBorde);
        jLabel3.setForeground(ColorFont);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        Border thickBorder = new LineBorder(grisPress, 54);
        jButton1.setBorder(thickBorder);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        Border thickBorder = new LineBorder(grisborde, 54);
        jButton1.setBorder(thickBorder);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        Border thickBorder = new LineBorder(grisborde, 54);
        jButton1.setBorder(thickBorder);
        jButton3.setBorder(thickBorde);
        jLabel2.setForeground(Color.BLACK);
        jLabel3.setForeground(ColorFont);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        Border thickBorder = new LineBorder(ColorSalida2, 54);
        jButton3.setBorder(thickBorder);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        Border thickBorder = new LineBorder(ColorSalida2, 54);
        jButton3.setBorder(thickBorder);
        jLabel3.setForeground(ColorFont);
        reback();
DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
int rows = model.getRowCount(); 
for(int i = rows - 1; i >=0; i--)
{
   model.removeRow(i); 
}
DefaultTableModel model2 = (DefaultTableModel)jTable2.getModel(); 
int rows2 = model2.getRowCount(); 
for(int i = rows2 - 1; i >=0; i--)
{
   model2.removeRow(i); 
}
        MENUadmin.controlVentana1=true;
        Border thickBorderX = new LineBorder(Color.WHITE, 5);
        jButton3.setBorder(thickBorderX);
        find.setText("");
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        Border thickBorder = new LineBorder(ColorSalida, 54);
        jButton3.setBorder(thickBorder);
        jButton1.setBorder(thickBorde);
        jLabel2.setForeground(ColorFont);
        jLabel3.setForeground(Color.WHITE);
 
       
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        Border thickBorder = new LineBorder(Color.BLUE, 54);
        jButton3.setBorder(thickBorder);
        jButton1.setBorder(thickBorde);
        jLabel3.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
    
   
    }//GEN-LAST:event_formMouseMoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
      // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jTable1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseMoved

    // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseMoved

    private void jLabel17MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseMoved
        Border thickBorderX = new LineBorder(Color.WHITE, 5);
        jButton1.setBorder(thickBorderX);
        jButton3.setBorder(thickBorderX);
        jLabel2.setForeground(ColorFont);
        jLabel3.setForeground(ColorFont);
        Border thickBorder = new LineBorder(delete, 60);
Border thickBorder2 = new LineBorder(add, 60);
Border thickBorder3 = new LineBorder(CBTNmenu, 60);
jButton10.setBorder(thickBorder);
jButton11.setBorder(thickBorder2);
jButton9.setBorder(thickBorder3);

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseMoved

    private void jLabel38MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MousePressed

    private void jLabel38MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseReleased
array_String = new String[jTable1.getRowCount()][jTable1.getColumnCount()];
array_Tipo = new String[jTable1.getRowCount()][jTable1.getColumnCount()];
array_Double = new Double[jTable1.getRowCount()][jTable1.getColumnCount()];
    int i = 0;
    int j = 0;
    for (i = 0; i < jTable1.getRowCount(); i++) {
        for (j = 0; j < 3; j++) {
            array_String[i][j] = (String) jTable1.getValueAt(i, j);
        }
    }
     int f = 0;
    int g = 0;
    for (f = 0; f < jTable1.getRowCount(); f++) {
        for (g = 0; g < 4; g++) {
            array_Double[f][g] = (Double) jTable1.getValueAt(f, g+3);
        }
    }
    
    for (f = 0; f < jTable1.getRowCount(); f++) {
        for (g = 0; g < 1; g++) {
            array_Tipo[f][g] = (String) jTable1.getValueAt(f, g+7);
        }
    }
    
ConfirmarVenta CV = new ConfirmarVenta(auxST,array_String,array_Tipo, array_Double,cdp, units,count,Cliente);

        if(jLabel5.getText().length()!=0){
CV.setVisible(true);
CV.setLocationRelativeTo(null);

}               // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseReleased

    private void jLabel38MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseMoved
        jLabel38.setToolTipText(null);  
jButton9.setBorder(focus);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseMoved

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MousePressed

    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseReleased

    private void jButton9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseMoved

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Border thickBorder = new LineBorder(delete, 60);
Border thickBorder2 = new LineBorder(add, 60);
Border thickBorder3 = new LineBorder(CBTNmenu, 60);
Border thickBorder4 = new LineBorder(Nums, 60);
jButton10.setBorder(thickBorder);
jButton11.setBorder(thickBorder2);
jButton9.setBorder(thickBorder3);
jButton4.setBorder(thickBorder4);
jButton5.setBorder(thickBorder4);




 // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jLabel39MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel39MousePressed

    private void jLabel39MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseReleased
if(jTable1.getSelectedRow() >= 0){
 rebackUnid();
 
 int r = jTable1.getSelectedRow();
             units.remove( r);
             DefaultTableModel modelo =(DefaultTableModel)jTable1.getModel(); 
             int rw = jTable1.getSelectedRow();
             modelo.removeRow(rw );
             jLabel5.setText("");
             sumaT = 0.0;
           int totalRow= jTable1.getRowCount();
        for(int i=0;i<(totalRow);i++)
        {
        double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,6)));
        sumaT= sumaT + sumatoria;
        auxST = Double.toString(sumaT);
        jLabel14.setVisible(true);
        jLabel6.setVisible(true);
        jLabel5.setVisible(true); 
        jLabel5.setText(auxST);
        }
            }        
         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel39MouseReleased

    private void jLabel39MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseMoved
  
jButton10.setBorder(focusD);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel39MouseMoved

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MousePressed

    private void jButton10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseReleased

    private void jButton10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseMoved

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel40MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40MousePressed

    private void jLabel40MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseReleased
int row = jTable2.getSelectedRow();
if(row != -1)
{
cod_prod = jTable2.getModel().getValueAt(row, 0).toString();
categor = jTable2.getModel().getValueAt(row, 1).toString();
product = jTable2.getModel().getValueAt(row, 2).toString();
PreV = Double.parseDouble(jTable2.getModel().getValueAt(row, 7).toString());
PreMay = Double.parseDouble(jTable2.getModel().getValueAt(row, 8).toString());
PreOro = Double.parseDouble(jTable2.getModel().getValueAt(row, 9).toString());
descu = Double.parseDouble(jTable2.getModel().getValueAt(row, 10).toString());
int cantidadTablaBusqueda = Integer.parseInt(jTable2.getModel().getValueAt(row, 5).toString());

DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
Object [] fila=new Object[8]; 
cantidadMAyor m= new cantidadMAyor();
unit = lcd.getText();
cantidad = cantidadTablaBusqueda;
                 MSGUnidadesStock menUnid = new MSGUnidadesStock(unit, Integer.toString(cantidad));
                 unidadesDeseadas = Integer.valueOf(lcd.getText()); 
                 

                 //if para veridifcar que unidades deseadas sean mayor a cero
                 if(unidadesDeseadas!= 0){
                     
                 //if para verificar que hayan existencias en bodega    
                 if(cantidad>= unidadesDeseadas ){
                     
                 //verificar que ningun checbox este seleccionado
                 if(!jCheckBox1.isSelected()&&!jCheckBox2.isSelected()&&!jCheckBox3.isSelected()){
                        tipoVent = "Normal";
                        totalVenta = Double.valueOf(unidadesDeseadas) * PreV;
                       operacion1 = cantidad - unidadesDeseadas;
                       units.add(operacion1);
                        jTable1.setRowHeight(25);
                        fila = new Object[8];
                        fila[0]=cod_prod;
                        fila[1]=categor; 
                        fila[2]=product; 
                        fila[3]=Double.valueOf(PreV);
                        fila[4]=Double.valueOf(0.0); 
                        fila[5]=Double.valueOf(unidadesDeseadas); 
                        fila[6]=totalVenta; 
                        fila[7]=tipoVent;  
                         sumaT = 0.0;
                        try{
                        Connection conex = DriverManager.getConnection(url, user, pass);
                        String Qury = "INSERT INTO tabla_aux SELECT *from producto where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        Statement sts =  conex.createStatement();
                        sts.executeUpdate(Qury);
                        String query = "update producto set unidades ='"+operacion1+"' where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        PreparedStatement preparedStmt = conex.prepareStatement(query);
                        preparedStmt.executeUpdate();
                        modelo.addRow(fila); 
                                 jTable1.setModel(modelo);
                                 lcd.setText("0");
                                 int totalRow= jTable1.getRowCount();
                                    for(int i=0;i<(totalRow);i++)
                                    {
                                    double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,6)));
                                    sumaT= sumaT + sumatoria;
                                    auxST = Double.toString(sumaT);
                                    jLabel14.setVisible(true);
                                    jLabel6.setVisible(true);
                                    jLabel5.setVisible(true); 
                                    jLabel5.setText(auxST);
                                    }
                                    cant=0;
                        }catch(SQLException es){
                        JOptionPane.showMessageDialog(this, es);
                        }
                     
                 }
                 //if para ver que tipo de checkbox descuento esta seleccionó    
                     if(jCheckBox1.isSelected()&&!jCheckBox2.isSelected()&&!jCheckBox3.isSelected()){
                     tipoVent = "Normal";
                     totalVenta = Double.valueOf(unidadesDeseadas) * PreV - descu;
                       operacion1 = cantidad - unidadesDeseadas;
                       units.add(operacion1);
                        jTable1.setRowHeight(25);
                        fila = new Object[8];
                        fila[0]=cod_prod;
                        fila[1]=categor; 
                        fila[2]=product; 
                        fila[3]=Double.valueOf(PreV);
                        fila[4]=Double.valueOf(descu); 
                        fila[5]=Double.valueOf(unidadesDeseadas); 
                        fila[6]=totalVenta; 
                        fila[7]=tipoVent;  
                         sumaT = 0.0;
                        try{
                        Connection conex = DriverManager.getConnection(url, user, pass);
                        String Qury = "INSERT INTO tabla_aux SELECT *from producto where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        Statement sts =  conex.createStatement();
                        sts.executeUpdate(Qury);
                        String query = "update producto set unidades ='"+operacion1+"' where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        PreparedStatement preparedStmt = conex.prepareStatement(query);
                        preparedStmt.executeUpdate();
                        modelo.addRow(fila); 
                                 jTable1.setModel(modelo);
                                 lcd.setText("0");
                                 int totalRow= jTable1.getRowCount();
                                    for(int i=0;i<(totalRow);i++)
                                    {
                                    double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,6)));
                                    sumaT= sumaT + sumatoria;
                                    auxST = Double.toString(sumaT);
                                    jLabel14.setVisible(true);
                                    jLabel6.setVisible(true);
                                    jLabel5.setVisible(true); 
                                    jLabel5.setText(auxST);
                                    }
                                    cant=0;
                        }catch(SQLException es){
                        JOptionPane.showMessageDialog(this, es);
                        }
                      }
                     
                     //if para ver que tipo de checkbox MAYOREO esta seleccionó    
                     if(jCheckBox2.isSelected()&&!jCheckBox1.isSelected()&&!jCheckBox3.isSelected()){
                       tipoVent = "Mayorista";
                       totalVenta = Double.valueOf(unidadesDeseadas) * PreMay;
                       operacion1 = cantidad - unidadesDeseadas;
                       units.add(operacion1);
                        jTable1.setRowHeight(25);
                        fila = new Object[8];
                        fila[0]=cod_prod;
                        fila[1]=categor; 
                        fila[2]=product; 
                        fila[3]=Double.valueOf(PreMay);
                        fila[4]=Double.valueOf(0.0); 
                        fila[5]=Double.valueOf(unidadesDeseadas); 
                        fila[6]=totalVenta; 
                        fila[7]=tipoVent;  
                         sumaT = 0.0;
                        try{
                        Connection conex = DriverManager.getConnection(url, user, pass);
                        String Qury = "INSERT INTO tabla_aux SELECT *from producto where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        Statement sts =  conex.createStatement();
                        sts.executeUpdate(Qury);
                        String query = "update producto set unidades ='"+operacion1+"' where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        PreparedStatement preparedStmt = conex.prepareStatement(query);
                        preparedStmt.executeUpdate();
                        modelo.addRow(fila); 
                                 jTable1.setModel(modelo);
                                 lcd.setText("0");
                                    int totalRow= jTable1.getRowCount();
                                    for(int i=0;i<(totalRow);i++)
                                    {
                                    double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,6)));
                                    sumaT= sumaT + sumatoria;
                                    auxST = Double.toString(sumaT);
                                    jLabel14.setVisible(true);
                                    jLabel6.setVisible(true);
                                    jLabel5.setVisible(true); 
                                    jLabel5.setText(auxST);
                                    }
                                    cant=0;
        
                        }catch(SQLException es){
                        JOptionPane.showMessageDialog(this, es);
                        }
                      }
                     //if para ver que tipo de checkbox ORO esta seleccionó    
                     if(jCheckBox3.isSelected()&&!jCheckBox1.isSelected()&&!jCheckBox2.isSelected()){
                       tipoVent = "Oro";
                       totalVenta = Double.valueOf(unidadesDeseadas) * PreOro;
                       operacion1 = cantidad - unidadesDeseadas;
                       units.add(operacion1);
                        jTable1.setRowHeight(25);
                        fila = new Object[8];
                        fila[0]=cod_prod;
                        fila[1]=categor; 
                        fila[2]=product; 
                        fila[3]=Double.valueOf(PreOro);
                        fila[4]=Double.valueOf(0.0); 
                        fila[5]=Double.valueOf(unidadesDeseadas); 
                        fila[6]=totalVenta; 
                        fila[7]=tipoVent;  
                         sumaT = 0.0;
                        try{
                        Connection conex = DriverManager.getConnection(url, user, pass);
                        String Qury = "INSERT INTO tabla_aux SELECT *from producto where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        Statement sts =  conex.createStatement();
                        sts.executeUpdate(Qury);
                        String query = "update producto set unidades ='"+operacion1+"' where codigo_producto='"+cod_prod+"' && producto='"+product+"'";
                        PreparedStatement preparedStmt = conex.prepareStatement(query);
                        preparedStmt.executeUpdate();
                        modelo.addRow(fila); 
                                 jTable1.setModel(modelo);
                                 lcd.setText("0");
                                 int totalRow= jTable1.getRowCount();
                                    for(int i=0;i<(totalRow);i++)
                                    {
                                    double sumatoria= Double.parseDouble(String.valueOf(jTable1.getValueAt(i,6)));
                                    sumaT= sumaT + sumatoria;
                                    auxST = Double.toString(sumaT);
                                    jLabel14.setVisible(true);
                                    jLabel6.setVisible(true);
                                    jLabel5.setVisible(true); 
                                    jLabel5.setText(auxST);
                                    }
                                    cant=0;
                        }catch(SQLException es){
                        JOptionPane.showMessageDialog(this, es);
                        }
                      } 
                     
                     //limpia y pone foco a label para buscar de nuevo y recarga la tabla de bsuqueda
                     search= find.getText();
                     buscarT(search);
                     find.setText("");
                     find.requestFocus();
        }
        else 
            menUnid.setVisible(true);
            menUnid.setLocationRelativeTo(null);
        }
        else 
           m.setVisible(true);
           m.setLocationRelativeTo(null);


   }
else
    JOptionPane.showMessageDialog(this,"No seleccionó ningun artículo");
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel40MouseReleased

    private void jLabel40MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseMoved
 
jButton11.setBorder(focusA);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40MouseMoved

    private void jButton11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MousePressed

    private void jButton11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseReleased

    private void jButton11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseMoved

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseDragged

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
x = evt.getX();
                y = evt.getY();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
if(cant>0){
    cant--;
    lcd.setText(Integer.toString(cant));
}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseReleased

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
cant++;
lcd.setText(Integer.toString(cant));         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
Color X1 =new Color(117,117,117);
Border thickBorder = new LineBorder(X1, 86);
jLabel21.setToolTipText(null); 
        jButton4.setBorder(thickBorder);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
Color X1 =new Color(117,117,117);
Border thickBorder = new LineBorder(X1, 86);
jLabel20.setToolTipText(null); 
        jButton5.setBorder(thickBorder);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
Color X1 =new Color(153,153,153);
Border thickBorder = new LineBorder(X1, 86);
jLabel20.setToolTipText(null); 
        jButton5.setBorder(thickBorder);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
  Color X1 =new Color(153,153,153);
Border thickBorder = new LineBorder(X1, 86);
jLabel21.setToolTipText(null); 
        jButton4.setBorder(thickBorder);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    private void jLabel39MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseEntered
jButton10.setBorder(focusD);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel39MouseEntered

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseMoved

    private void jTable2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2PropertyChange

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findActionPerformed

    private void findKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findKeyPressed
              // TODO add your handling code here:
    }//GEN-LAST:event_findKeyPressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseDragged

    private void findKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findKeyReleased
search= find.getText();
        buscarT(search);        // TODO add your handling code here:
    }//GEN-LAST:event_findKeyReleased

    private void lcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcdActionPerformed

    private void lcdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lcdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lcdKeyPressed

    private void lcdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lcdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lcdKeyReleased

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hacer_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hacer_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hacer_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hacer_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hacer_ventas(NN).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField find;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    private javax.swing.JTextField lcd;
    // End of variables declaration//GEN-END:variables


public ArrayList<String> consultaClientes() throws SQLException {
String seleccion = "SELECT DISTINCT nombre FROM clientes";
PreparedStatement ps = cnx.prepareStatement(seleccion);
ArrayList<String> ls = new ArrayList<String>(); 
ResultSet rs = ps.executeQuery();
while(rs.next()){
ls.add(rs.getString("nombre"));
}
return ls;
}

public ArrayList<String> consulta() throws SQLException {
String seleccion = "SELECT DISTINCT Marca FROM producto where Unidades>0";
PreparedStatement ps = cnx.prepareStatement(seleccion);
ArrayList<String> ls = new ArrayList<String>(); 
ResultSet rs = ps.executeQuery();
while(rs.next()){
ls.add(rs.getString("Marca"));
}
return ls;
}



public void reback(){
            
            try{    
            cnx = DriverManager.getConnection(url, user,pass);
             String sql = "Select *from tabla_aux";
             Statement st = cnx.prepareStatement(sql);
             ResultSet res = st.executeQuery(sql);
             
            while (res.next()){
            ID = res.getString(1);  
            MK = res.getString(3);  
            MD = res.getString(4);  
            UD  = res.getInt(8);
            
      Class.forName("com.mysql.jdbc.Driver");         
      conI = DriverManager.getConnection(url, user,pass);
      String query = "update producto set Unidades = ? where codigo_producto = ? && categoria = ? && producto = ?";
      PreparedStatement preparedStmt = conI.prepareStatement(query);
      preparedStmt.setInt   (1, UD);
      preparedStmt.setString   (2, ID);
      preparedStmt.setString   (3, MK);
      preparedStmt.setString   (4, MD);
      preparedStmt.executeUpdate();
      
      
        Connection conex = DriverManager.getConnection(url, user, pass);
        String Qury = "TRUNCATE tabla_aux";
        Statement sts =  conex.createStatement();
        sts.executeUpdate(Qury);
            }
            }
            catch(SQLException ex){JOptionPane.showMessageDialog(this,ex);} catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,ex);
            }
           }

public void rebackUnid(){
      int UD,rw = jTable1.getSelectedRow(); 
      String ID, MK, MD, PRD;
      
            try{    
            cnx = DriverManager.getConnection(url, user,pass);
             String sql = "Select *from tabla_aux";
             Statement st = cnx.prepareStatement(sql);
             ResultSet res = st.executeQuery(sql);
             
            while (res.next()){
            ID = res.getString(1);  
            MK = res.getString(3);  
            MD = res.getString(4);  
            UD  = res.getInt(8);
      if(MK.equals(String.valueOf(jTable1.getValueAt(rw,1))) && MD.equals(String.valueOf(jTable1.getValueAt(rw,2)))){
      conI = DriverManager.getConnection(url, user,pass);
      String query = "update producto set unidades = ? where codigo_producto='"+String.valueOf(jTable1.getValueAt(rw,0))+"' && categoria='"+String.valueOf(jTable1.getValueAt(rw,1))+"'"+"&& producto='"+String.valueOf(jTable1.getValueAt(rw,2))+"'";

      PreparedStatement preparedStmt = conI.prepareStatement(query);
      preparedStmt.setInt   (1, UD);
      preparedStmt.executeUpdate();
      }
            }
            }
            catch(SQLException ex){
            JOptionPane.showMessageDialog(this,ex+" Update");
            }
    try{
      conI = DriverManager.getConnection(url, user,pass);
        String Qury = "Delete from tabla_aux where codigo_producto='"+String.valueOf(jTable1.getValueAt(rw,0))+"' && categoria='"+String.valueOf(jTable1.getValueAt(rw,1))+"'"+"&& producto='"+String.valueOf(jTable1.getValueAt(rw,2))+"'";
        Statement sts =  conI.createStatement();
        sts.executeUpdate(Qury);
        }
        catch(SQLException ex){
        JOptionPane.showMessageDialog(this,ex+ " Truncate");
        }
        }


public void buscarT(String search){
        String busq = search;
        DefaultTableModel modelo = new DefaultTableModel();
        jTable2.setModel(modelo);
        Connection cnx = null;
        if (cnx == null) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cnx = DriverManager.getConnection(url, user,pass);
             String sql = "SELECT codigo_producto, categoria, producto, proveedor, ubicacion, unidades, fecha_vencimiento, precio_venta, precio_mayoreo, precio_oro, descuento from producto where codigo_producto like '"+busq+"%' or "+"producto like '"+busq+"%'"+" or "+"categoria like '"+busq+"%'";
             Statement st = cnx.prepareStatement(sql);
             ResultSet res = st.executeQuery(sql);
             ResultSetMetaData rsMd = res.getMetaData();
             int cantidadColumnas = rsMd.getColumnCount();
             for (int i = 1; i <= cantidadColumnas; i++) {
            modelo.addColumn(rsMd.getColumnLabel(i));
         }
         while (res.next()){
         Object[] fila = new Object[cantidadColumnas];
         for (int i = 0; i < cantidadColumnas; i++) {
         fila[i]=res.getObject(i+1);
         }
              modelo.addRow(fila);
             
             }
             } catch (ClassNotFoundException ex) {
             throw new ClassCastException(ex.getMessage());
             } catch (SQLException ex) { 
                Logger.getLogger(LoginGT.class.getName()).log(Level.SEVERE, null, ex);
            } 
            }   
    }

}
